name: deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write # 允许推送到 gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - name: Enable bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('.ruby-version') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install -g @mermaid-js/mermaid-cli

      - name: Setup deploy environment
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 设置源码分支
          if [[ "${GITHUB_REF}" == refs/pull/*/merge ]]; then
            echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
            echo "NO_PUSH=--no-push" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
            echo "NO_PUSH=" >> $GITHUB_ENV
          else
            echo "SRC_BRANCH=unknown" >> $GITHUB_ENV
            echo "NO_PUSH=--no-push" >> $GITHUB_ENV
          fi

          echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

      - name: Deploy website
        run: |
          echo "Deploying from $SRC_BRANCH to $DEPLOY_BRANCH"
          bash bin/deploy --verbose $NO_PUSH --src "$SRC_BRANCH" --deploy "$DEPLOY_BRANCH"
